### ISSUE TITLE
Integrating an item

### ISSUE THREAD

**Issue by extant1** [FWolfe/RealGunsMod#1]
I'm trying to modify Nolan's old ORGM Silencer/Supressor mod but it was designed for OrMtnMan's version.  I've looked over the old version and your rewrite and it's very well done.  I'd like to add it to the component table but don't completely understand how the game works and I haven't used lua since ye olde minecraft's computercraft.

From what I can tell calling `ORGM.Component.register` is the way to go so the component spawns in containers and pre-attached to guns.  If I do something like the code below would it be similar to how Nolan was just inserting "Silencer.Silencer" into the tables?

```
if (ORGM.Component) then
	ORGM.Component.register('Silencer', { moduleName = 'Silencer',});
end
```

```
if(CivModTable) then table.insert(CivModTable, "Silencer.Silencer"); end
if (NonCivModTable) then table.insert(NonCivModTable, "Silencer.Silencer"); end
if (WeaponUpgrades) then
	if(WeaponUpgrades["Ber92"] ~= nil) then table.insert(WeaponUpgrades["Ber92"], "Silencer.Silencer"); end
        ...
end
```

**Comment by FWolfe** [comment]
There shouldn't be any need to modify Nolans mod. It was designed for the legacy version, but ORGM includes a built in patch in [ORGMClientCompatibilityPatches.lua](https://github.com/FWolfe/RealGunsMod/blob/master/ORGM/media/lua/client/ORGMClientCompatibilityPatches.lua) for the silencing effect, removing the OnWeaponSwing event added by the silencer mod and replacing it with a saner system. 
The register call is done in [ORGMCallbacks.lua](https://github.com/FWolfe/RealGunsMod/blob/master/ORGM/media/lua/shared/2LoadOrder/ORGMCallbacks.lua)

```lua
--[[- Loads any shared compatibility patches for mods.
This is triggered by Events.OnGameBoot.
]]
Callbacks.loadPatches = function()
    if ORGM.isModLoaded("ORGMSilencer") and ORGM.Settings.UseSilencersPatch then
        local item = getScriptManager():FindItem("Silencer.Silencer")
        if item then item:setDisplayName("Suppressor") end
        item = getScriptManager():FindItem("Silencer.HMSilencer")
        if item then item:setDisplayName("Home Made Suppressor") end

        -- TODO: adding a sound here is no good, soundbanks have been loaded
        ORGM.Sounds.add("silenced_shot", {maxrange = 50, maxreverbrange = 50, priority = 9})
        ORGM.Component.register("Silencer", {moduleName = "Silencer", lastChanged = 20})
    end
    ORGM.log(ORGM.INFO, "Event: All shared patches injected")
end
```
Effectively, I've had to undo all of his work and have the patch code handling everything. It should be working fine on the current versions of the silencer mod.

Edit: you'll note the homemade suppressors are not registered. This is to keep them from spawning, and adding 2 types of suppressors into the spawn table and further increasing the number that spawn.

**Comment by extant1** [comment]
Sorry for the delay in response you are correct.  I saw the comments on the mod page and noticed the errors loading the files and none of the "if" blocks were being loaded and set out to fix it but none of that is necessary as you already have it covered, thank you. 👍
